export const STRINGS = {
  common: {
    yes: 'Jah',
    no: 'Ei',
    backToHome: 'Tagasi avalehele',
  },
  form: {
    fullName: 'Täisnimi',
    contactPhone: 'Kontakttelefon',
    validDrivingLicense: 'Kehtiv juhiluba',
    cars: 'Autod',
    multiSelectHint: 'Mitme valiku tegemiseks kasuta Ctrl/Cmd klahvi.',
    unnamedCar: '(nimetu auto)',
  },
  home: {
    title: 'Vormid',
    addForm: 'Lisa vorm',
    emptyState: 'Ühtegi vormi pole selles sessioonis veel täidetud.',
  },
  formCard: {
    showDetails: 'Näita üksikasju',
  },
  create: {
    title: 'Vormi loomine',
    loadingCars: 'Laen automarke ja -mudeleid...',
    loadCarsError: 'Automarkide laadimine ebaõnnestus. Proovi uuesti.',
    saveError: 'Vormi salvestamine ebaõnnestus. Kontrolli andmeid ja proovi uuesti.',
    submit: 'Kinnita',
    submitting: 'Salvestan...',
  },
  edit: {
    title: 'Vormi muutmine',
    back: 'Tagasi',
    missingId: 'Vormi ID puudub.',
    loadingEntry: 'Laen vormi andmeid...',
    loadEntryError: 'Vormi andmete laadimine ebaõnnestus. Proovi uuesti.',
    notFound: 'Selle ID-ga vormi ei leitud.',
    saveError: 'Muudatuste salvestamine ebaõnnestus. Proovi uuesti.',
    submit: 'Salvesta muudatused',
    submitting: 'Salvestan...',
  },
  details: {
    title: 'Vormi üksikasjad',
    missingId: 'Vormi ID puudub.',
    loading: 'Laen vormi üksikasju...',
    notFound: 'Selle ID-ga vormi ei leitud.',
    selectedCars: 'Valitud autod',
    noSelectedCars: 'Autosid ei ole valitud.',
    deleteError: 'Vormi kustutamine ebaõnnestus. Proovi uuesti.',
    deleteConfirm: 'Kas oled kindel, et soovid selle vormi kustutada?',
    edit: 'Muuda',
    delete: 'Kustuta',
    deleting: 'Kustutan...',
  },
} as const;
